"""LangGraph nodes for the seven agents (plan section 5).

Each agent's node is generated by :func:`make_node`, which wires the shared
prompt + Gemini structured-output call + SSE streaming + persistence.
"""

from __future__ import annotations

from app.models.enums import AgentName

from .base import NodeFn, make_node

architect_node = make_node(AgentName.ARCHITECT)
planner_node = make_node(AgentName.PLANNER)
backend_node = make_node(AgentName.BACKEND)
frontend_node = make_node(AgentName.FRONTEND)
qa_node = make_node(AgentName.QA)
documentation_node = make_node(AgentName.DOCUMENTATION)
cto_review_node = make_node(AgentName.CTO_REVIEW)

NODES: dict[AgentName, NodeFn] = {
    AgentName.ARCHITECT: architect_node,
    AgentName.PLANNER: planner_node,
    AgentName.BACKEND: backend_node,
    AgentName.FRONTEND: frontend_node,
    AgentName.QA: qa_node,
    AgentName.DOCUMENTATION: documentation_node,
    AgentName.CTO_REVIEW: cto_review_node,
}

__all__ = [
    "NODES",
    "make_node",
    "architect_node",
    "planner_node",
    "backend_node",
    "frontend_node",
    "qa_node",
    "documentation_node",
    "cto_review_node",
]
